# Generated by Django 3.2.13 on 2022-05-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'proposal',
            },
        ),
    ]
